#ifndef LCOMPILERS_LSP_AST_PARSER_DECLARATIONS_H
#define LCOMPILERS_LSP_AST_PARSER_DECLARATIONS_H

namespace LCompilers::LanguageServiceProvider::AST {
  enum class AccessIdType;
  enum class ActionStmtType;
  enum class ACValueType;
  enum class AllocateObjectType;
  enum class ArraySpecType;
  enum class AttrSpecType;
  enum class BlankInterpEditDescType;
  enum class BozLiteralConstantType;
  enum class CaseExprType;
  enum class CaseSelectorType;
  enum class CaseValueRangeType;
  enum class CaseValueType;
  enum class CharLengthType;
  enum class CharSelectorType;
  enum class CharStringEditDescType;
  enum class CloseSpecType;
  enum class ComponentArraySpecType;
  enum class ComponentAttrSpecType;
  enum class ConnectSpecType;
  enum class ConstantType;
  enum class ControlEditDescType;
  enum class DataEditDescType;
  enum class DataIDoObjectType;
  enum class DataStmtConstantType;
  enum class DataStmtObjectType;
  enum class DeclarationConstructType;
  enum class DefinedOperatorType;
  enum class DoConstructType;
  enum class DoStmtType;
  enum class EndDoType;
  enum class EntityDeclType;
  enum class EquivalenceObjectType;
  enum class ExecutableConstructType;
  enum class ExecutionPartConstructType;
  enum class ExternalSubprogramType;
  enum class FilePositioningType;
  enum class FormatItemType;
  enum class FormatType;
  enum class ImagPartType;
  enum class ImplicitPartStmtType;
  enum class ImplicitStmtType;
  enum class InputItemType;
  enum class InquireSpecType;
  enum class InquireStmtType;
  enum class InternalSubprogramType;
  enum class IntrinsicOperatorType;
  enum class IoControlSpecType;
  enum class IoImpliedDoObjectType;
  enum class IoUnitType;
  enum class KindParamType;
  enum class LengthSelectorType;
  enum class LiteralConstantType;
  enum class LoopControlType;
  enum class ModuleSubprogramType;
  enum class NonblockDoConstructType;
  enum class OnlyType;
  enum class OutputItemType;
  enum class ParentStringType;
  enum class PositionEditDescType;
  enum class PositionSpecType;
  enum class PrimaryType;
  enum class ProgramUnitType;
  enum class ReadStmtType;
  enum class RealLiteralType;
  enum class RealPartType;
  enum class SavedEntityType;
  enum class SectionSubscriptType;
  enum class SharedTermDoConstructType;
  enum class SignEditDescType;
  enum class SignificandType;
  enum class SpecificationStmtType;
  enum class StopCodeType;
  enum class SubobjectType;
  enum class TargetType;
  enum class TypeParamValueType;
  enum class TypeSpecType;
  enum class UseStmtType;
  enum class VariableType;
  struct AccessConnectSpec;
  struct AccessId;
  struct AccessIdList;
  struct AccessInquireSpec;
  struct AccessorPartRef;
  struct AccessSpec;
  struct AccessStmt;
  struct ACDoVariable;
  struct ACImpliedDo;
  struct ACImpliedDoControl;
  struct ACImpliedDoControlThirdExpr;
  struct ActionConnectSpec;
  struct ActionInquireSpec;
  struct ActionStmt;
  struct ActionTermDoConstruct;
  struct ACValue;
  struct ACValueList;
  struct ADataEditDesc;
  struct AddOp;
  struct AddOperand;
  struct AddOperandAndMultOp;
  struct AdvanceIoSpec;
  struct AllocatableStmt;
  struct AllocateLowerBound;
  struct AllocateLowerBoundTo;
  struct AllocateObject;
  struct AllocateObjectList;
  struct AllocateShapeSpec;
  struct AllocateShapeSpecList;
  struct AllocateStmt;
  struct AllocateUpperBound;
  struct Allocation;
  struct AllocationList;
  struct AndOp;
  struct AndOperand;
  struct ArithmeticIfStmt;
  struct ArrayConstructor;
  struct ArrayElement;
  struct ArrayName;
  struct ArrayNameAndDeferredShapeSpecList;
  struct ArrayNameAndDeferredShapeSpecLists;
  struct ArrayNameSpec;
  struct ArrayNameSpecList;
  struct ArraySection;
  struct ArraySpec;
  struct ArraySpecDecl;
  struct ArrayVariableName;
  struct AssignedGotoStmt;
  struct AssignedInitializationExpr;
  struct AssignmentStmt;
  struct AssignStmt;
  struct AssumedShapeSpec;
  struct AssumedShapeSpecList;
  struct AssumedSizeSpec;
  struct AttrSpec;
  struct BackspaceExternalFileUnit;
  struct BackspacePositionSpecList;
  struct BackspaceStmt;
  struct BDataEditDesc;
  struct BinaryConstant;
  struct BlankConnectSpec;
  struct BlankInquireSpec;
  struct BlankInterpEditDesc;
  struct Block;
  struct BlockData;
  struct BlockDataStmt;
  struct BlockDoConstruct;
  struct BozLiteralConstant;
  struct ByStride;
  struct C;
  struct CallStmt;
  struct CaseConstruct;
  struct CaseConstructName;
  struct CaseConstructNameDefinition;
  struct CaseExpr;
  struct CaseSelector;
  struct CaseStmt;
  struct CaseStmtAndBlock;
  struct CaseValue;
  struct CaseValueRange;
  struct CaseValueRangeList;
  struct CaseValueTo;
  struct CaseValueToCaseValue;
  struct CharacterSelector;
  struct CharConstant;
  struct CharExpr;
  struct CharInitializationExpr;
  struct CharLength;
  struct CharLiteralConstant;
  struct CharSelector;
  struct CharStringEditDesc;
  struct CharVariable;
  struct CHRepChar;
  struct CloseSpec;
  struct CloseSpecList;
  struct CloseStmt;
  struct CommonBlockName;
  struct CommonBlockObject;
  struct CommonBlockObjectList;
  struct CommonStmt;
  struct ComplexLiteralConstant;
  struct ComplexSelector;
  struct ComponentArraySpec;
  struct ComponentAttrSpec;
  struct ComponentAttrSpecArraySpec;
  struct ComponentAttrSpecList;
  struct ComponentDecl;
  struct ComponentDeclArraySpec;
  struct ComponentDeclList;
  struct ComponentDefStmt;
  struct ComponentDefStmtAccessSpec;
  struct ComponentDefStmtDecl;
  struct ComponentName;
  struct ComputedGotoStmt;
  struct ConcatOp;
  struct ConditionalLoopControl;
  struct ConnectSpec;
  struct ConnectSpecList;
  struct Constant;
  struct ConstantSubobject;
  struct ContainsStmt;
  struct ContinueStmt;
  struct ControlEditDesc;
  struct CycleStmt;
  struct D;
  struct DataEditDesc;
  struct DataIDoObject;
  struct DataIDoObjectList;
  struct DataIDoVariable;
  struct DataImpliedDo;
  struct DataRef;
  struct DataStmt;
  struct DataStmtConstant;
  struct DataStmtObject;
  struct DataStmtObjectList;
  struct DataStmtRepeat;
  struct DataStmtRepeatStar;
  struct DataStmtSet;
  struct DataStmtValue;
  struct DataStmtValueList;
  struct DDataEditDesc;
  struct DeallocateStmt;
  struct DeclarationConstruct;
  struct DeclaredImplicitNone;
  struct DeclaredImplicitSpecList;
  struct DefaultCharExpr;
  struct DefaultCharVariable;
  struct DefaultIntVariable;
  struct DefaultLogicalVariable;
  struct DeferredShapeSpec;
  struct DeferredShapeSpecList;
  struct DefinedAccessIdList;
  struct DefinedBinaryOp;
  struct DefinedOperator;
  struct DefinedSavedEntityList;
  struct DefinedUnaryOp;
  struct DelimConnectSpec;
  struct DelimInquireSpec;
  struct DelimitedAttrSpec;
  struct DelimitedParenthesizedLabelList;
  struct DelimitedRenameList;
  struct DelimitedScalarIntExpr;
  struct DelimitedStatIsStatVariable;
  struct DerivedTypeDef;
  struct DerivedTypeStmt;
  struct DerivedTypeStmtAccessSpec;
  struct DerivedTypeStmtDecl;
  struct DigitString;
  struct DimensionStmt;
  struct DirectInquireSpec;
  struct DoBlock;
  struct DoBody;
  struct DoConstruct;
  struct DoConstructName;
  struct DoConstructNameDefinition;
  struct DoStmt;
  struct DoTermActionStmt;
  struct DoTermSharedStmt;
  struct DotM;
  struct DoublePrecision;
  struct DoVariable;
  struct DummyArgName;
  struct DummyArgNameList;
  struct E;
  struct EDataEditDesc;
  struct Ee;
  struct ElseIfStmt;
  struct ElseIfStmtAndBlock;
  struct ElseStmt;
  struct ElseStmtAndBlock;
  struct ElsewhereStmt;
  struct ElsewhereStmtAndAssignmentStmts;
  struct EmphasizedCommonBlockName;
  struct EmphasizedCommonBlockNameAndObjectList;
  struct ENDataEditDesc;
  struct EndBlockDataStmt;
  struct EndDo;
  struct EndDoStmt;
  struct EndfileExternalFileUnit;
  struct EndfilePositionSpecList;
  struct EndfileStmt;
  struct EndFunctionStmt;
  struct EndIfStmt;
  struct EndIoSpec;
  struct EndModuleStmt;
  struct EndProgramStmt;
  struct EndSelectStmt;
  struct EndSubroutineStmt;
  struct EndTypeStmt;
  struct EndWhereStmt;
  struct EntityDecl;
  struct EntityDeclList;
  struct EntryStmt;
  struct EnumeratedLoopControl;
  struct EorIoSpec;
  struct EquivalenceObject;
  struct EquivalenceSet;
  struct EquivalenceSetList;
  struct EquivalenceStmt;
  struct EquivOp;
  struct EquivOperand;
  struct EquivOperandAndOrOp;
  struct ErrConnectSpec;
  struct ErrInquireSpec;
  struct ErrIoSpec;
  struct ErrPositionSpec;
  struct ESDataEditDesc;
  struct ExecutableConstruct;
  struct ExecutableProgram;
  struct ExecutionPart;
  struct ExecutionPartConstruct;
  struct ExistInquireSpec;
  struct ExitStmt;
  struct ExplicitShapeLowerBound;
  struct ExplicitShapeLowerBoundTo;
  struct ExplicitShapeSpec;
  struct ExplicitShapeSpecList;
  struct ExplicitShapeSpecListDelimited;
  struct ExplicitShapeUpperBound;
  struct Exponent;
  struct ExponentLetter;
  struct Expr;
  struct ExprAndDefinedBinaryOp;
  struct ExprList;
  struct ExtendedIntrinsicOp;
  struct ExternalFileUnit;
  struct ExternalStmt;
  struct ExternalSubprogram;
  struct FDataEditDesc;
  struct FileConnectSpec;
  struct FileInquireSpec;
  struct FileNameExpr;
  struct Format;
  struct FormatAssignment;
  struct FormatIoSpec;
  struct FormatItem;
  struct FormatItemList;
  struct FormatSpecification;
  struct FormatStmt;
  struct FormattedInquireSpec;
  struct FormConnectSpec;
  struct FormInquireSpec;
  struct FunctionEntityDecl;
  struct FunctionName;
  struct FunctionReference;
  struct FunctionStmt;
  struct FunctionSubprogram;
  struct GDataEditDesc;
  struct GenericSpec;
  struct GotoStmt;
  struct HexConstant;
  struct IDataEditDesc;
  struct IfConstruct;
  struct IfConstructName;
  struct IfConstructNameDefinition;
  struct IfStmt;
  struct IfThenStmt;
  struct ImagPart;
  struct ImplicitPart;
  struct ImplicitPartStmt;
  struct ImplicitSpec;
  struct ImplicitSpecList;
  struct ImplicitStmt;
  struct InitializationExpr;
  struct InnerSharedDoConstruct;
  struct InputItem;
  struct InquireSpec;
  struct InquireSpecList;
  struct InquireStmt;
  struct InquireStmtWithInquireSpecList;
  struct InquireStmtWithOutputItemList;
  struct IntConstant;
  struct IntegerSelector;
  struct IntentSpec;
  struct IntentSpecDecl;
  struct IntentStmt;
  struct InterfaceBlock;
  struct InternalFileUnit;
  struct InternalSubprogram;
  struct InternalSubprogramPart;
  struct IntExpr;
  struct IntInitializationExpr;
  struct IntitializationExpr;
  struct IntLiteralConstant;
  struct IntrinsicOperator;
  struct IntrinsicStmt;
  struct IntVariable;
  struct IoControlSpec;
  struct IoControlSpecList;
  struct IoImpliedDo;
  struct IoImpliedDoControl;
  struct IoImpliedDoObject;
  struct IoImpliedDoObjectList;
  struct IostatConnectSpec;
  struct IostatInquireSpec;
  struct IostatIoSpec;
  struct IostatPositionSpec;
  struct IoUnit;
  struct K;
  struct KindAssignment;
  struct KindParam;
  struct KindSelector;
  struct KindWithOptLength;
  struct KP;
  struct Label;
  struct LabelDoStmt;
  struct LabelList;
  struct LDataEditDesc;
  struct LeadingKind;
  struct LeftPartialSignificand;
  struct LengthAssignment;
  struct LengthSelector;
  struct LengthWithKind;
  struct LengthWithTypeParamValue;
  struct LetterSpec;
  struct LetterSpecList;
  struct Level1Expr;
  struct Level2Expr;
  struct Level2ExprAndAddOp;
  struct Level3Expr;
  struct Level3ExprAndConcatOp;
  struct Level3ExprAndRelOp;
  struct Level4Expr;
  struct Level5Expr;
  struct Level5ExprAndEquivOp;
  struct LiteralConstant;
  struct LocalNameAs;
  struct LogicalExpr;
  struct LogicalInitializationExpr;
  struct LogicalLiteralConstant;
  struct LogicalSelector;
  struct LogicalVariable;
  struct LoopControl;
  struct LoopControlStepSize;
  struct M;
  struct MainProgram;
  struct MaskExpr;
  struct Module;
  struct ModuleStmt;
  struct ModuleSubprogram;
  struct ModuleSubprogramPart;
  struct MultOp;
  struct MultOperand;
  struct N;
  struct Name;
  struct NamedConstant;
  struct NamedConstantDef;
  struct NamedConstantDefList;
  struct NamedInquireSpec;
  struct NameInquireSpec;
  struct NamelistAssignment;
  struct NamelistGroupName;
  struct NamelistGroupNameAndObjectList;
  struct NamelistGroupObject;
  struct NamelistGroupObjectList;
  struct NamelistIoSpec;
  struct NamelistStmt;
  struct NextrecInquireSpec;
  struct NonblockDoConstruct;
  struct NonlabelDoStmt;
  struct NotOp;
  struct NullifyStmt;
  struct NumberInquireSpec;
  struct NumericExpr;
  struct NX;
  struct ObjectEntityDecl;
  struct ObjectName;
  struct ObjectNameAndDeferredShapeSpecList;
  struct ObjectNameAndParenthesizedArraySpec;
  struct OctalConstant;
  struct ODataEditDesc;
  struct Only;
  struct OnlyList;
  struct OpenedInquireSpec;
  struct OpenStmt;
  struct OptionalLocalNameAsUseName;
  struct OptionalModuleName;
  struct OptionalProgramName;
  struct OptionalStmt;
  struct OrOp;
  struct OrOperand;
  struct OrOperandAndAndOp;
  struct OuterSharedDoConstruct;
  struct OutputItem;
  struct OutputItemList;
  struct PadConnectSpec;
  struct PadInquireSpec;
  struct ParameterStmt;
  struct ParenthesizedAllocateShapeSpecList;
  struct ParenthesizedArraySpec;
  struct ParenthesizedCaseValueRangeList;
  struct ParenthesizedDeferredShapeSpecList;
  struct ParenthesizedExplicitShapeSpecList;
  struct ParenthesizedExpr;
  struct ParenthesizedSectionSubscriptList;
  struct ParenthesizedSubstringRange;
  struct ParenthesizedTypeParamValue;
  struct ParentString;
  struct PartName;
  struct PartRef;
  struct PauseStmt;
  struct PointerAssignmentStmt;
  struct PointerObject;
  struct PointerObjectList;
  struct PointerStmt;
  struct PositionConnectSpec;
  struct PositionEditDesc;
  struct PositionInquireSpec;
  struct PositionSpec;
  struct PositionSpecList;
  struct PowerOp;
  struct PowerOpAndMultOperand;
  struct Primary;
  struct PrintStmt;
  struct PrivateSequenceStmt;
  struct ProgramStmt;
  struct ProgramUnit;
  struct R;
  struct RangeUpperLetter;
  struct RDataEditDesc;
  struct ReadInquireSpec;
  struct ReadStmt;
  struct ReadStmtWithFormat;
  struct ReadStmtWithSpecList;
  struct ReadwriteInquireSpec;
  struct RealLiteralConstant;
  struct RealLiteralWithoutSignificand;
  struct RealLiteralWithSignificand;
  struct RealPart;
  struct RealSelector;
  struct RecIoSpec;
  struct ReclConnectSpec;
  struct ReclInquireSpec;
  struct RelOp;
  struct Rename;
  struct RenameList;
  struct RepCharSeq;
  struct ReturnStmt;
  struct RewindExternalFileUnit;
  struct RewindPositionSpecList;
  struct RewindStmt;
  struct RFormatItemList;
  struct RightPartialSignificand;
  struct RSlash;
  struct SavedEntity;
  struct SavedEntityList;
  struct SaveStmt;
  struct ScalarConstant;
  struct ScalarDefaultCharExpr;
  struct ScalarDefaultIntVariable;
  struct ScalarIntConstant;
  struct ScalarIntConstantName;
  struct ScalarIntExpr;
  struct ScalarIntInitializationExpr;
  struct ScalarIntLiteralConstant;
  struct ScalarIntVariable;
  struct ScalarLogicalExpr;
  struct ScalarNumericExpr;
  struct ScalarStructureComponent;
  struct ScalarVariable;
  struct ScalarVariableName;
  struct SectionSubscript;
  struct SectionSubscriptList;
  struct SelectCaseStmt;
  struct SequentialInquireSpec;
  struct SharedTermDoConstruct;
  struct Sign;
  struct SignedDigitString;
  struct SignedIntLiteralConstant;
  struct SignEditDesc;
  struct SignedRealLiteralConstant;
  struct Significand;
  struct SizeIoSpec;
  struct SpecificationExpr;
  struct SpecificationPart;
  struct SpecificationStmt;
  struct StarCharLength;
  struct StarCharLengthDelimited;
  struct StatusConnectSpec;
  struct StatVariable;
  struct StmtFunctionStmt;
  struct StopCode;
  struct StopStmt;
  struct Stride;
  struct StructureComponent;
  struct StructureConstructor;
  struct Subobject;
  struct SubroutineStmt;
  struct SubroutineSubprogram;
  struct Subscript;
  struct SubscriptTriplet;
  struct Substring;
  struct SubstringRange;
  struct Target;
  struct TargetStmt;
  struct TLn;
  struct Tn;
  struct ToCaseValue;
  struct TrailingExponent;
  struct TrailingKind;
  struct TRn;
  struct TypeDecl;
  struct TypeDeclarationStmt;
  struct TypeName;
  struct TypeParamValue;
  struct TypeParamWithScalarIntInitExpr;
  struct TypeSelector;
  struct TypeSpec;
  struct Underscore;
  struct UnformattedInquireSpec;
  struct UnitAssignment;
  struct UnitConnectSpec;
  struct UnitInquireSpec;
  struct UnitIoSpec;
  struct UnitPositionSpec;
  struct UseAllStmt;
  struct UseOnlyStmt;
  struct UseStmt;
  struct Variable;
  struct VariableName;
  struct VectorSubscript;
  struct W;
  struct WhereConstruct;
  struct WhereConstructStmt;
  struct WhereStmt;
  struct WriteInquireSpec;
  struct WriteStmt;
  struct ZDataEditDesc;
} // namespace LCompilers::LanguageServiceProvider::AST

#endif // LCOMPILERS_LSP_AST_PARSER_DECLARATIONS_H
